
"""Car_body_type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PGyA_zcA__WRxJU9WSSuYas-QUDAPvL
"""


import os
from pathlib import Path

# Adjust if your path is different
ROOT = Path("/content/drive/MyDrive/car_body_data")

if not ROOT.exists():
    # Try to locate it
    print("Not at expected path. Searching...")
    for p in Path("/content/drive/MyDrive").rglob("stanford*"):
        print(p)
else:
    print(f"Root: {ROOT}")
    print("Top-level contents:")
    for item in sorted(ROOT.iterdir()):
        print(f"  {'[DIR] ' if item.is_dir() else '[FILE]'} {item.name}")

from pathlib import Path
import os

DATASET = Path("/content/drive/MyDrive/car_body_data/stanford_cars_type")

print("Contents of stanford_cars_type/:")
for item in sorted(DATASET.iterdir()):
    if item.is_dir():
        n_files = len(list(item.iterdir()))
        print(f"  [DIR]  {item.name}  ({n_files} items)")
    else:
        print(f"  [FILE] {item.name}")

# Also peek at the CSV
import pandas as pd
csv_path = Path("/content/drive/MyDrive/car_body_data/stanford_cars_type.csv")
df = pd.read_csv(csv_path)
print("\nCSV shape:", df.shape)
print("CSV columns:", list(df.columns))
print("\nFirst 3 rows:")
print(df.head(3))
print("\nClass distribution (if there's a label column):")
print(df.iloc[:, -1].value_counts() if df.shape[1] > 1 else "only 1 column")

print(Path("/content/drive/MyDrive/car_body_data/data_info.txt").read_text())

import os
import shutil
import random
from pathlib import Path

random.seed(42)

SOURCE = Path("/content/drive/MyDrive/car_body_data/stanford_cars_type")
DEST = Path("/content/drive/MyDrive/car_body_data/split")

SPLITS = {"train": 0.70, "valid": 0.15, "test": 0.15}
MERGE_OTHER_INTO_CAB = True  # set False to keep "Other" as its own class

# --- Step 1: Prepare destination ---
if DEST.exists():
    shutil.rmtree(DEST)
DEST.mkdir(parents=True)

# --- Step 2: Discover class folders ---
classes = sorted([d.name for d in SOURCE.iterdir() if d.is_dir()])
print(f"Found {len(classes)} classes: {classes}\n")

# --- Step 3: Collect files per class (optionally merging Other -> Cab) ---
class_files = {}
for cls in classes:
    files = [f for f in (SOURCE / cls).iterdir()
             if f.suffix.lower() in {".jpg", ".jpeg", ".png"}]
    target_cls = "Cab" if (MERGE_OTHER_INTO_CAB and cls == "Other") else cls

    if target_cls not in class_files:
        class_files[target_cls] = []
    class_files[target_cls].extend(files)

print(f"After merge: {len(class_files)} classes\n")

# --- Step 4: Split each class ---
for cls, files in sorted(class_files.items()):
    random.shuffle(files)
    n = len(files)
    n_train = int(n * SPLITS["train"])
    n_val = int(n * SPLITS["valid"])

    buckets = {
        "train": files[:n_train],
        "valid": files[n_train:n_train + n_val],
        "test":  files[n_train + n_val:],
    }

    for split, flist in buckets.items():
        out_dir = DEST / split / cls
        out_dir.mkdir(parents=True, exist_ok=True)
        for f in flist:
            shutil.copy2(f, out_dir / f.name)

    print(f"{cls:<15} total={n:5d} | "
          f"train={len(buckets['train']):5d} | "
          f"val={len(buckets['valid']):4d} | "
          f"test={len(buckets['test']):4d}")

print(f"\n✅ Split complete: {DEST}")

# Verify
for split in ["train", "valid", "test"]:
    split_dir = DEST / split
    total = sum(len(list((split_dir / c).iterdir())) for c in split_dir.iterdir())
    print(f"  {split:<6}: {total} images, {len(list(split_dir.iterdir()))} classes")


# Example: Data augmentation and loading
import torch
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

# Data transforms
train_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
val_test_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Create datasets and dataloaders
train_dir = '/content/drive/MyDrive/car_body_data/split/train' # Adjust path if necessary
val_dir = '/content/drive/MyDrive/car_body_data/split/valid'
test_dir = '/content/drive/MyDrive/car_body_data/split/test'

train_dataset = datasets.ImageFolder(train_dir, transform=train_transform)
val_dataset = datasets.ImageFolder(val_dir, transform=val_test_transform)
test_dataset = datasets.ImageFolder(test_dir, transform=val_test_transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

# Model setup
model = models.resnet50(pretrained=True)
num_ftrs = model.fc.in_features
num_classes = len(train_dataset.classes)
model.fc = nn.Linear(num_ftrs, num_classes)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
# ... training loop ...

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import time

EPOCHS = 25
best_val_acc = 0.0
best_path = "/content/drive/MyDrive/car_body_data/best_model.pth"
classes = train_dataset.classes

scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    losses, preds, labels = [], [], []
    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for imgs, lbls in loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            if train:
                optimizer.zero_grad()
            out = model(imgs)
            loss = criterion(out, lbls)
            if train:
                loss.backward()
                optimizer.step()
            losses.append(loss.item() * imgs.size(0))
            preds.extend(out.argmax(1).cpu().numpy())
            labels.extend(lbls.cpu().numpy())
    n = len(labels)
    return sum(losses)/n, accuracy_score(labels, preds), f1_score(labels, preds, average="macro")

print(f"Classes ({len(classes)}): {classes}")
print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}\n")

for epoch in range(1, EPOCHS + 1):
    t0 = time.time()
    tr_loss, tr_acc, _ = run_epoch(train_loader, train=True)
    vl_loss, vl_acc, vl_f1 = run_epoch(val_loader, train=False)
    scheduler.step()

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)

    marker = ""
    if vl_acc > best_val_acc:
        best_val_acc = vl_acc
        torch.save(model.state_dict(), best_path)
        marker = "  best"

    print(f"Epoch {epoch:02d}/{EPOCHS} | "
          f"train loss={tr_loss:.4f} acc={tr_acc:.4f} | "
          f"val loss={vl_loss:.4f} acc={vl_acc:.4f} f1={vl_f1:.4f} | "
          f"{time.time()-t0:.0f}s{marker}")

print(f"\nBest val accuracy: {best_val_acc:.4f}")

# ---------- Test ----------
model.load_state_dict(torch.load(best_path))
te_loss, te_acc, te_f1 = run_epoch(test_loader, train=False)

print(f"\n{'='*60}")
print(f"FINAL TEST RESULTS")
print(f"{'='*60}")
print(f"  Loss:      {te_loss:.4f}")
print(f"  Accuracy:  {te_acc:.4f}")
print(f"  F1-macro:  {te_f1:.4f}")

# Per-class report
model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for imgs, lbls in test_loader:
        out = model(imgs.to(device))
        all_preds.extend(out.argmax(1).cpu().numpy())
        all_labels.extend(lbls.numpy())

print(f"\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=classes, digits=4))

# Confusion matrix
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix — Test Set")
plt.ylabel("True"); plt.xlabel("Predicted")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/car_body_data/confusion_matrix.png", dpi=120)
plt.show()

# Training curves
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(history["train_loss"], label="train")
ax1.plot(history["val_loss"], label="val")
ax1.set_title("Loss"); ax1.set_xlabel("Epoch"); ax1.legend()
ax2.plot(history["train_acc"], label="train")
ax2.plot(history["val_acc"], label="val")
ax2.set_title("Accuracy"); ax2.set_xlabel("Epoch"); ax2.legend()
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/car_body_data/training_curves.png", dpi=120)
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, f1_score
import time

ROOT = "/content/drive/MyDrive/car_body_data/split"
BEST_PATH = "/content/drive/MyDrive/car_body_data/best_model.pth"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Data
train_tf = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(0.2, 0.2, 0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])
eval_tf = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

train_ds = datasets.ImageFolder(f"{ROOT}/train", transform=train_tf)
val_ds   = datasets.ImageFolder(f"{ROOT}/valid", transform=eval_tf)
classes = train_ds.classes

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=2, pin_memory=True)

# Load saved model
model = models.resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(classes))
model.load_state_dict(torch.load(BEST_PATH, map_location=DEVICE))
model = model.to(DEVICE)

print(f"Loaded: {BEST_PATH}")
print(f"Classes ({len(classes)}): {classes}")

# Fresh optimizer for the final stretch
optimizer = optim.SGD(model.parameters(), lr=1e-4, momentum=0.9, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=7)
criterion = nn.CrossEntropyLoss()

def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    losses, preds, labels = [], [], []
    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for imgs, lbls in loader:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            if train:
                optimizer.zero_grad()
            out = model(imgs)
            loss = criterion(out, lbls)
            if train:
                loss.backward()
                optimizer.step()
            losses.append(loss.item() * imgs.size(0))
            preds.extend(out.argmax(1).cpu().numpy())
            labels.extend(lbls.cpu().numpy())
    n = len(labels)
    return sum(losses)/n, accuracy_score(labels, preds), f1_score(labels, preds, average="macro")

# Baseline check
vl_loss, vl_acc, vl_f1 = run_epoch(val_loader, train=False)
print(f"Current val: loss={vl_loss:.4f} acc={vl_acc:.4f} f1={vl_f1:.4f}\n")

best_val_acc = vl_acc

for epoch in range(19, 26):
    t0 = time.time()
    tr_loss, tr_acc, _ = run_epoch(train_loader, train=True)
    vl_loss, vl_acc, vl_f1 = run_epoch(val_loader, train=False)
    scheduler.step()

    marker = ""
    if vl_acc > best_val_acc:
        best_val_acc = vl_acc
        torch.save(model.state_dict(), BEST_PATH)
        marker = "  best"

    print(f"Epoch {epoch:02d}/25 | "
          f"train loss={tr_loss:.4f} acc={tr_acc:.4f} | "
          f"val loss={vl_loss:.4f} acc={vl_acc:.4f} f1={vl_f1:.4f} | "
          f"{time.time()-t0:.0f}s{marker}")

print(f"\nBest val accuracy: {best_val_acc:.4f}")

import torch, time
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# 1. GPU check
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Device: {torch.cuda.get_device_name(0)}")
    
else:
    print("⚠️  NO GPU — running on CPU. That's why it's slow.")

# 2. DataLoader speed test
ROOT = "/content/drive/MyDrive/car_body_data/split"
eval_tf = transforms.Compose([
    transforms.Resize(256), transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])
ds = datasets.ImageFolder(f"{ROOT}/train", transform=eval_tf)
loader = DataLoader(ds, batch_size=32, shuffle=False, num_workers=2)

t0 = time.time()
for i, (imgs, lbls) in enumerate(loader):
    if i == 10:  # 10 batches
        break
elapsed = time.time() - t0
print(f"\n10 batches loaded in {elapsed:.1f}s → {elapsed/10*178:.0f}s per epoch just for loading")

import torch
import torch.nn as nn
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

ROOT = "/content/drive/MyDrive/car_body_data/split"
BEST_PATH = "/content/drive/MyDrive/car_body_data/best_model.pth"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

eval_tf = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

test_ds = datasets.ImageFolder(f"{ROOT}/test", transform=eval_tf)
test_loader = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=2)
classes = test_ds.classes

model = models.resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(classes))
model.load_state_dict(torch.load(BEST_PATH, map_location=DEVICE))
model = model.to(DEVICE).eval()

criterion = nn.CrossEntropyLoss()
losses, preds, labels = [], [], []
with torch.no_grad():
    for imgs, lbls in test_loader:
        imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
        out = model(imgs)
        losses.append(criterion(out, lbls).item() * imgs.size(0))
        preds.extend(out.argmax(1).cpu().numpy())
        labels.extend(lbls.cpu().numpy())

print(f"{'='*60}")
print(f"FINAL TEST RESULTS")
print(f"{'='*60}")
print(f"  Accuracy:  {accuracy_score(labels, preds):.4f}")
print(f"  F1-macro:  {f1_score(labels, preds, average='macro'):.4f}")
print(f"\n{classification_report(labels, preds, target_names=classes, digits=4)}")

cm = confusion_matrix(labels, preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix — Test Set")
plt.ylabel("True"); plt.xlabel("Predicted")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/car_body_data/confusion_matrix.png", dpi=120)
plt.show()

# Save the model info needed for deployment
import json
with open("/content/drive/MyDrive/car_body_data/model_info.json", "w") as f:
    json.dump({
        "classes": classes,
        "backbone": "resnet50",
        "num_classes": len(classes),
        "input_size": 224,
        "normalize_mean": [0.485, 0.456, 0.406],
        "normalize_std": [0.229, 0.224, 0.225],
    }, f, indent=2)
print("\nSaved model_info.json for deployment")
